// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADH9PRFM3y-j4ahS6MpUGaSphGOX8o_CA',
    appId: '1:486257027843:android:ecce0784892007e5509736',
    messagingSenderId: '486257027843',
    projectId: 'fxswift-c4689',
    storageBucket: 'fxswift-c4689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlyDAi4erwoD3FhebKBYv6MoH8yZ6kwVA',
    appId: '1:486257027843:ios:e4413c4a3b7f5800509736',
    messagingSenderId: '486257027843',
    projectId: 'fxswift-c4689',
    storageBucket: 'fxswift-c4689.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlyDAi4erwoD3FhebKBYv6MoH8yZ6kwVA',
    appId: '1:486257027843:ios:e4413c4a3b7f5800509736',
    messagingSenderId: '486257027843',
    projectId: 'fxswift-c4689',
    storageBucket: 'fxswift-c4689.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTz2_aFVdILUY1yKMda2M3CbxczPPGpdk',
    appId: '1:486257027843:web:ddfab88e91df7545509736',
    messagingSenderId: '486257027843',
    projectId: 'fxswift-c4689',
    authDomain: 'fxswift-c4689.firebaseapp.com',
    storageBucket: 'fxswift-c4689.firebasestorage.app',
  );
}
